### ISSUE TITLE
Whats happening with the db?

### ISSUE THREAD

**Issue by DanEvans485** [G-Bro/OpenDM-Server#25] opened 2020-02-08 12:05 UTC
We did discuss this but do we have a planned structure yet?

**Comment by G-Bro** [comment] 2020-02-08 12:09
Not yet. I was planning to start mapping it all out later today

**Comment by DanEvans485** [comment] 2020-02-08 12:11
I will see if I can decipher when we said yesterday and update that chart I know you wanted to split monsters and characters but it should still work.

**Comment by Newobc** [comment] 2020-02-08 13:02
duplicate of #14

**Closed by Newobc** 2020-02-08 13:02 UTC
Labels: question, structure
